# **Ejercicios de la evaluación del Módulo 2 Sprint 1**
## **Numpy**
### **Lidya Descals**

---

1. Importa la librería de NumPy.


In [11]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.


In [12]:
unidimensional = np.random.randint(1, 100, (10))
unidimensional

array([87,  6, 48, 92, 70, 37,  8, 37, 13,  6])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.


In [13]:
# Entiendo que el enunciado contiene un error y que se trata de cambiar los números impares por el valor "impar".

pares_impares = np.empty((10), object)

for num in range(unidimensional.shape[0]):
    if unidimensional[num] % 2 == 0:
        pares_impares[num] = "Par"
    else:
        pares_impares[num] = "Impar"

pares_impares


array(['Impar', 'Par', 'Par', 'Par', 'Par', 'Impar', 'Par', 'Impar',
       'Impar', 'Par'], dtype=object)

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.


In [14]:
bidimensional = np.reshape(pares_impares, (2,5))
bidimensional

array([['Impar', 'Par', 'Par', 'Par', 'Par'],
       ['Impar', 'Par', 'Impar', 'Impar', 'Par']], dtype=object)

5. Extrae los elementos comunes de los siguientes arrays

    ```
    array1 = np.array([1,2,3,2,3,4,3,4,5,6])
    array2 = np.array([7,2,10,2,7,4,9,4,9,8])


In [32]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(array1, array2)

array([2, 4])


6. Extraed los elementos que están en el array1 pero no en el array2.


In [16]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.


In [40]:
print(f"Los índices donde encontramos elementos que aparecen en los dos arrays son {np.where(array1 == array2)[0]}, tanto para el array1 como para el array2")

Los índices donde encontramos elementos que aparecen en los dos arrays son [1 3 5 7], tanto para el array1 como para el array2


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.


In [47]:
enteros = np.random.randint(0, 51, (3,5))
print(enteros)
print(f"Estos valores son menores de 10: {np.where(enteros < 10)},\n y estos mayores de 40: {np.where(enteros > 40)}")

[[35  5 25 11 48]
 [30  1 43  6 44]
 [13 23  0  5 14]]
Estos valores son menores de 10: (array([0, 1, 1, 2, 2]), array([1, 1, 3, 2, 3])),
 y estos mayores de 40: (array([0, 1, 1]), array([4, 2, 4]))


9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.


In [51]:
decimales = np.random.uniform(5, 10, (5, 3)).round(2)
decimales

array([[5.32, 7.08, 7.49],
       [9.82, 9.06, 9.5 ],
       [6.68, 9.12, 5.1 ],
       [9.84, 6.7 , 7.93],
       [7.79, 7.88, 5.38]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20


In [52]:
tridimensional = np.random.randint(1, 21,(2, 4, 7))
tridimensional

array([[[13, 19,  3, 20,  3, 20,  4],
        [ 9,  2, 19,  8,  5,  9, 20],
        [19,  6, 11, 20,  7,  6, 11],
        [10, 12,  4, 20,  3, 13,  3]],

       [[ 8, 17,  1, 16, 15, 11,  4],
        [ 6,  5, 12, 18, 12, 14,  2],
        [10, 20, 13, 16,  4, 15, 14],
        [10, 18,  9, 15, 10, 17,  1]]])

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [59]:
np.transpose(tridimensional, (1, 2, 0))

array([[[13,  8],
        [19, 17],
        [ 3,  1],
        [20, 16],
        [ 3, 15],
        [20, 11],
        [ 4,  4]],

       [[ 9,  6],
        [ 2,  5],
        [19, 12],
        [ 8, 18],
        [ 5, 12],
        [ 9, 14],
        [20,  2]],

       [[19, 10],
        [ 6, 20],
        [11, 13],
        [20, 16],
        [ 7,  4],
        [ 6, 15],
        [11, 14]],

       [[10, 10],
        [12, 18],
        [ 4,  9],
        [20, 15],
        [ 3, 10],
        [13, 17],
        [ 3,  1]]])